### PR TITLE
Fix Rabbitmq installation & use https endpoint

### LINKED ISSUE #1485: Rabbitmq Script requires update
## Versions
  - Vagrant: Vagrant 2.2.7
  - Provider: Hyper-V
  - Homestead: 20.04

## Host operating system
Windows

## Vagrant destroy & up output
Not available

## Expected behavior
`apt update` should work without errors

## Actual behavior
`apt update` is giving 404 error as focal is not present in https://dl.bintray.com/rabbitmq/debian
it is available in http://dl.bintray.com/rabbitmq-erlang/debian

## Steps to reproduce
1. Enable rabbitmq in Homestead.yml
2. Run `vagrant provision`
3. Run `vagrant ssh`
4. Run `apt update`

## References
- https://github.com/laravel/homestead/blob/1d97324b44cf1817a3dfbf092a8e6ad30e04a47d/scripts/features/rabbitmq.sh#L18

### PR DESCRIPTION
**Pull request by martianatwork**
Fixes #1485

### CODE REVIEW

File: scripts/features/rabbitmq.sh [hunk 1]
```diff
@@ -14,8 +14,8 @@ chown -Rf vagrant:vagrant /home/vagrant/.homestead-features
 # Setup Repositories
 wget -q -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | sudo apt-key add -
 wget -q -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -
-echo "deb http://dl.bintray.com/rabbitmq-erlang/debian bionic erlang" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
-echo "deb https://dl.bintray.com/rabbitmq/debian $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/rabbitmq.list
+echo "deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
+echo "deb https://dl.bintray.com/rabbitmq-erlang/debian $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/rabbitmq.list
```
Comment (svpernova09) [inline scripts/features/rabbitmq.sh:18]: Based on https://www.rabbitmq.com/install-debian.html I think we should remove these 2 lines and use:

```
sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list <<EOF
## Installs the latest Erlang 23.x release.
## Change component to "erlang-22.x" to install the latest 22.x version.
## "bionic" as distribution name should work for any later Ubuntu or Debian release.
## See the release to distribution mapping table in RabbitMQ doc guides to learn more.
deb https://dl.bintray.com/rabbitmq-erlang/debian focal erlang
## Installs latest RabbitMQ release
deb https://dl.bintray.com/rabbitmq/debian focal main
EOF
```

**Review by svpernova09 — CHANGES_REQUESTED** [review]

File: scripts/features/rabbitmq.sh (hunk 1 above)
Comment (martianatwork) [reply scripts/features/rabbitmq.sh]: @svpernova09 Changes are done

**Review by svpernova09 — APPROVED** [review]
Works on my machine, thanks!
